### ISSUE TITLE
TIKV as the distributed storage engine

### ISSUE THREAD

**Issue by rock59** [genjidb/genji#137]
Hi
TIKV is one of the best distributed transnational kv stores available with a nice golang driver. I dont know much about genji's internal but I guess TIKV can be a good candidate to become the distributed storage engine for genji.

[tikv.org](https://tikv.org/)
[https://github.com/tikv/tikv](https://github.com/tikv/tikv)
[tikv.org/docs/4.0/reference/clients/go](https://tikv.org/docs/4.0/reference/clients/go/)
[github.com/tikv/client-go](https://github.com/tikv/client-go)

**Comment by joe-getcouragenow** [comment]
I was thinking more about just using genji and adding the ability for it to be distributed using https://github.com/lni/dragonboat

I do not know the ins and outs of genji too much, but because the engines ate now abstracted from the runtime, it MAY be possible to use dragonboat ( https://github.com/lni/dragonboat ) at the runtime level with genji and so support all the engines being distributed.

That would be really useful i feel because you can have the same DB on the Server ( in a distributed setup) and at the CDN and on the end user devices.   Very dry !! 

The movement of data from the DB Cluster downstream to the CDN and User devices is normally done by checking the Change-feed coming from dragonboat or genji, and then sending the change to the downstream DB.
This golang library does this based on MongoDB, and so can feed change events into other specialised DB's that do other often required things to build a high quality system.
https://github.com/rwynn/monstache
https://rwynn.github.io/monstache-site/

If @asdine or others have any thoughts i woudl love to hear them, because genji i think has great potential for reuse.

**Comment by ivanjaros** [comment]
tikv is written in rust. it makes no sense to use is as backend for this go library that acts as wrapper for 3rd paty storage-level go libraries like bolt or badger.

**Comment by rock59** [comment]
@ivanjaros TIDB as a Mysql compatible query engine is also written in Go and uses TiKV as its storage layer. TiKV is a global distributed transactional multi-group raft key-value database and can scale to 100+ PB of data. It would be nice to consider TiKV from early stages of GenjiDB development to make GenjiDb an enterprise grade document database.

**Comment by ivanjaros** [comment]
tidb is completely different beast. bringing C in here makes no sense since this is a midget in comparison with that Titanium folk are doing. it's like comparing your every day pickup truck and Caterpillar 797B :D

**Comment by rock59** [comment]
Therer is no need to use C or CGo. TiKV uses GRPC and provides a stable Go client written entirely in pure Go.

[tikv.org/docs/4.0/reference/clients/go](tikv.org/docs/4.0/reference/clients/go)
[github.com/tikv/client-go](github.com/tikv/client-go)

**Comment by ivanjaros** [comment]
well, i am not the author. i personally see absolutely no point in this. but maybe i am missing something here.

**Comment by gedw99** [comment]
Dragonboat works with genji and will make it distributed with a little bit of integration.

The reason you need few changes is because dragonboat supports badger.
Under the hood dragonboat uses pebble. It’s all all golang and no CGO.
Pebble is the new dB for cockroachdb that does RAFT based replication.

So then the API that you use with genji in embedded mode or replicated mode is the same. 

I am planing to put up the code on github this weekend. It’s not finished yet but it’s a starting point.

If you want to help your most welcome

**Comment by rock59** [comment]
Dragonboat is fast and promising but unless you reinvent the wheel and implement a multi-group raft store with Dragonboat, you cannot achieve the performance, scalability and reliability of TiKV. 
Dragonboat single group raft store is suitable for small clusters (one master and 2 and up to 4 slvaes) because performance of single group raft-based stores degrade with to many slaves . TiKV is multi-master and achieve this with multi-group raft ,regions , region splitting and more

**Comment by drauschenbach** [comment]
For years I've also been considering writing an Etcd storage adapter for Genji. But because Etcd, like TiKV, is a remote storage service rather than an embedded storage library, I agree with @ivanjaros that such adapters don't make sense in this repo.

What we need is assurance that the engine factory construction and wiring methods will work when we spawn new Git repos to hold other various storage engine adapters.

**Comment by gedw99** [comment]
This team have NATS and Genji together to get a distributed Genji.

the project is here: https://github.com/simpleiot/simpleiot

Its quite cool how it works.

the DB and NATS subjects are mapped together it seems here: https://github.com/simpleiot/simpleiot/blob/master/nats/subject.go

@cbrake  (https://github.com/cbrake) has done an amazing effort to make a self hosted solution that can run anywhere and yet be able to be reconfigured.

**Comment by asdine** [comment]
Closing this issue as now Genji focuses only on Pebble
