### ISSUE TITLE
Allow memoryengine transactions without locking

### ISSUE THREAD

**Issue by tie** [genjidb/genji#244]
Currently we can’t write tests for concurrent transactions since `memoryengine` acquires lock on `Begin`. We should allow creating memoryengine instance that doesn’t lock so that we can test ACID properties of concurrent (but not necessarily parallel) transactions.

Note that with #231 it would be possible to pass such option via `context.Context`.

Related: #243

**Comment by asdine** [comment]
This is actually pretty complicated, because that would basically force us to implement MVCC in the memoryengine, which by itself is a huge project.
The current memory engine provides the same guarantees as BoltDB or SQLite, which is one concurrent writer and multiple concurrent readers.
Is there something that you think is missing in the memoryengine?

**Comment by tie** [comment]
It’s indeed hard for the general case, but the point is to be able to synchronously test concurrent transactions for cases like #243. Currently it should suffice to clone the underlying BTree on `Begin` and return an error on `Commit` if another transaction modified the tree. This should (mostly) match the behavior in BadgerDB.

Perhaps this could also be a separate implementation in `enginetest`.

**Comment by asdine** [comment]
The memory engine is now lock-free
