### ISSUE TITLE
go get problem: unknown revision v0.9.0

### ISSUE THREAD

**Issue by cbrake** [genjidb/genji#303]
# What version of Genji are you using?

`v0.8.1-0.20201029082836-14c47075848a`

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I'm trying to run a project using the latest gengi/badgerengine with the following in `go.mod`:

```
        github.com/genjidb/genji v0.8.1-0.20201029082836-14c47075848a
        github.com/genjidb/genji/engine/badgerengine v0.8.1-0.20201029082836-14c47075848a
```

### What did you expect to see?

Expected program to run.

### What did you see instead?

```
go: github.com/genjidb/genji/engine/badgerengine@v0.8.1-0.20201029082836-14c47075848a requires
        github.com/genjidb/genji@v0.9.0: reading github.com/genjidb/genji/go.mod at revision v0.9.0: unknown revision v0.9.0
```

This can also be seen by running:

```
go get github.com/genjidb/genji/engine/badgerengine@master

go get: github.com/genjidb/genji/engine/badgerengine@v0.8.1-0.20201029082836-14c47075848a requires
        github.com/genjidb/genji@v0.9.0: reading github.com/genjidb/genji/go.mod at revision v0.9.0: unknown revision v0.9.0

```

My go modules understanding is a little weak, so wondering what I'm doing wrong here ...

### What Go version and environment are you using?

`go1.15.2` on Arch Linux

**Comment by tie** [comment]
We have dependency versions in nested modules updated ahead of release. That is, engine/badgerengine in commits after v0.8.0 tag depends on (not released yet) v0.9.0.

This setup works for local builds because we use [replace directive](https://golang.org/ref/mod#go-mod-file-replace) in `go.mod`.

>`replace` directives only apply in the main module's go.mod file and are ignored in other modules.

https://github.com/genjidb/genji/blob/14c47075848a5cd4b1ca782cf9af67cb0ac069d2/engine/badgerengine/go.mod#L11

Adding the following rules should work for “out-of-tree” projects that want to use the latest changes.
```
require (
        github.com/genjidb/genji v0.9.0
        github.com/genjidb/genji/engine/badgerengine v0.9.0
)

replace (
        github.com/genjidb/genji => github.com/genjidb/genji v0.8.1-0.20201029082836-14c47075848a
        github.com/genjidb/genji/engine/badgerengine => github.com/genjidb/genji/engine/badgerengine v0.8.1-0.20201029082836-14c47075848a
)
```

**Comment by cbrake** [comment]
thanks @tie -- that works perfectly. Also was able to get `go run github.com/genjidb/genji/cmd/genji` working by using a similar replace, which is handy for running the correct version of genji in my project.

Why does `github.com/genjidb/genji/engine/badgerengine` have its own `go.mod`?

**Comment by asdine** [comment]
> Why does github.com/genjidb/genji/engine/badgerengine have its own go.mod?

It was initially done to decouple Badger from Genji. A few releases ago, compiling a simple main with Genji took [4 seconds](https://medium.com/a-journey-with-go/go-builds-linkers-timeline-b312084ddf7d) because some of Badger dependencies use CGO.
Then I figured it would make sense to make it it's own module as it's just an engine implementation.

**Comment by cbrake** [comment]
that makes a lot of sense -- thanks for the explanation!
