### ISSUE TITLE
Support composite primary keys

### ISSUE THREAD

**Issue by drauschenbach** [genjidb/genji#35]
This seems like it would be easy to accommodate in the generated `PrimaryKey()` functions.

Here's what [Gorm compound key annotations](http://gorm.io/docs/composite_primary_key.html) look like.

**Comment by asdine** [comment]
Yes that's planned 👍 I started with simple indexes, then I'll redesign the index package to support compound indexes and more index algorithms.

**Comment by cbrake** [comment]
are integers the only primary key type supported right now?

is there a way to store a UUID as the primary key? github.com/google/uuid stores UUIDs as 16 bytes, but I suppose could also store as a string. Are UUIDs a good idea for a DB like this, or are sequential ints better for keys? If I recall correctly, bolt is more efficient if you append records rather than insert them in the middle of a bucket, so if this is the case, a int sequential key may be better in some cases.

**Comment by asdine** [comment]
No, you can use any scalar type as a primary key.
Example:

```sql
CREATE TABLE foo (
  some_id TEXT PRIMARY KEY NOT NULL
)
```

**Comment by asdine** [comment]
Support for composite primary keys has been added to [v0.14.0](https://github.com/genjidb/genji/releases/tag/v0.14.0) (cf: 8983d68daf1d030e5a2282ac39cdf76d637bdac8)
