### ISSUE TITLE
Website https://genji.dev/ is outdated

### ISSUE THREAD

**Issue by willie68** [genjidb/genji#450]
### What version of Genji are you using?
Not relevant

### What did you do?
Simple browse from Google to genji website

### What did you expect to see?
A representation fo the actual state of the development, because, when you look for information, this is normally the first contact with this project.

### What did you see instead?
Some information on the site are outdated, e.g. First Page Documentation, Getting started (part with badgerDB) which will lead you in the wrong direction. 
It's not a big issue, but it makes a bad first impression if the initial information on a project are not up-to-date.

**Comment by willie68** [comment]
Hm,i see, the 0.14.1 version is working with bbolt.

**Comment by asdine** [comment]
@willie68 Thanks for reporting this issue. The `main` branch is the development branch and we are in the process of removing support for bbolt and badger and focusing on pebble.
I understand the confusion though, since this is the first thing one sees when they reach the readme.
The website will shortly be updated once the support for pebble will be properly implemented.

In the meantime, 0.14.1 still has support for bolt and badger
