### ISSUE TITLE
Consider switching to a different K/V store

### ISSUE THREAD

**Issue by Elara6331** [genjidb/genji#486]
### Proposal

Currently, Genji uses Pebble as its K/V store. Pebble is maintained by CockroachDB, and they have said many times that it is meant to match the roadmap of CockroachDB itself, and that features outside of that are a low priority. As I mentioned in #485, Pebble prevents Genji from compiling on 32-bit platforms such as `GOARCH=386` and `GOARCH=arm`. It also fails to compile on `riscv64`. This is because Pebble uses build tags to detect 64-bit architectures, and every architecture has to be added explicitly to each file that uses them. The developers of Pebble have stated that this is not a priority for them.

I propose a switch to a different K/V store that compiles on more platforms, such as https://github.com/etcd-io/bbolt, or the addition of an interface to allow users to choose whichever implementation they want.

### Motivation

Nearly all other databases compile and run on 32-bit platforms. This change would alleviate all platform restrictions imposed by Pebble. There are many 32-bit machines and even some 64-bit machines that weren't able to use Genji before but will be able to if this is implemented.

**Comment by paralin** [comment]
I preferred having a common engine interface package (and enginetest) - this used to be the case in Genji, but recent commits removed it and centralized everything around pebble.

**Comment by asdine** [comment]
Closing this issue as Pebble now supports 32 bit architectures.

As for the main issue here, the switch to Pebble was necessary because some important features were lacking in Bolt / Badger. Also, maintaining several store implementations was really time consuming.

Once the database API is more stable, I will probably try to isolate Pebble as much as possible and let others provide other store implementations but it might never happen.

More information [here](https://github.com/genjidb/genji/releases/tag/v0.15.0)
