### ISSUE TITLE
Bug when comparing non-booleans with booleans

### ISSUE THREAD

**Issue by yaziine** [genjidb/genji#97]
Some comparisons between some non-booleans type with booleans returns the wrong value:
```
genji> select "" = false;
{
  "\"\" = false": false // should be true
}
genji> select "foo" = true;
{
  "\"foo\" = true": false // should be true
}
genji> select "foo" > false;
{
  "\"foo\" \u003e false": false // should be true
}
genji> select [] = false;
{
  "[] = false": false // should be true
}
genji> select [1,2,3] = true;
{
  "[1,2,3] = true": false // should be true
}
genji> select {} = false;
{
  "{} = false": false // should be true
}
genji> select {a: 1} = true;
{
  "{a: 1} = true": false // should be true
}
```

This is definitely not an exhaustive list, I probably forgot some edge cases.

**Comment by asdine** [comment]
Actually, these are not bugs. Comparison only applies to compatible types:

- numbers, durations, and booleans together
- text and blob together
- arrays together
- documents together
- null together

Any comparison between incompatible types must return `false`.
This also means that comparing with a boolean has nothing to do with determining if a value is truthy or falsy.

The reason behind that is, because we are storing documents that might have different types for the same field, it is important to compare apples with apples, and oranges with oranges

If I'm running this query for example, I only want documents where the group is a text or blob:

```
SELECT * FROM foo WHERE group != "admin";
```

In this one, I'll only have results where age is a number, a boolean, or a duration. (This is not ideal because this is still too broad, I believe this deserves an issue of its own):

```
SELECT * FROM foo WHERE age < 18;
```

The goal is to ensure the results are always predictable: When I write `WHERE age < 18`, I'm expecting documents with numeric ages.

**Comment by yaziine** [comment]
So probably the [documentation](https://genji.dev/docs/genji-sql/expressions/#comparing-with-a-boolean) is not up-to-date though?

**Comment by asdine** [comment]
> So probably the documentation is not up-to-date though?

That's an understatement. 💯 
The documentation is far from being up to date, and yes this definitely deserves a chapter there.
